require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{bundle,rails,rake}'
    - 'config.ru'
    - 'Rakefile'

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/EnvironmentVariableAccess:
  Enabled: false
